import {
  Client, Opportunity, Activity, Followup, InternalTask,
  TeamMember, BusinessSegment, User, CRMDocument,
  FleetSeaterCapacity, BillingFrequency, DeployedFleetContract
} from '../types/crm';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'CLT-1001',
    code: 'CLT-1001',
    name: 'ABC Manufacturing Ltd',
    clientType: 'Existing Client',
    industry: 'Manufacturing & Heavy Industry',
    segment: 'Employee Transportation',
    city: 'Pune',
    state: 'Maharashtra',
    region: 'West',
    tier: 'Tier 1 (Enterprise)',
    turnoverCr: 450,
    employees: 3200,
    status: 'Active',
    accountOwner: 'Rahul Sharma',
    website: 'www.abcmanufacturing.demo',
    address: 'Plot 45, Chakan Industrial Area Phase II, Pune',
    createdDate: '2025-11-15',
    contacts: [
      { id: 'CON-01', name: 'Rajesh Kulkarni', designation: 'VP - Operations & Admin', email: 'rajesh.k@abcmanufacturing.demo', phone: '+91 98231 44550', isPrimary: true },
      { id: 'CON-02', name: 'Sneha Patil', designation: 'Senior Manager - HR & Transport', email: 'sneha.p@abcmanufacturing.demo', phone: '+91 98231 44551' }
    ],
    deployedFleets: [
      {
        id: 'FLT-001',
        seaterCapacity: '17 Seater – AC',
        vehicleCount: 4,
        shiftFormat: 'General Shift (9:00 AM - 6:00 PM)',
        location: 'Chakan Plant 1 & 2',
        monthlyRatePerVehicleINR: 65000,
        totalMonthlyBillingINR: 260000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 18,
        extraHourRateINR: 120,
        tollParking: 'Exclusive / At Actuals',
        contractStartDate: '2025-12-01',
        contractEndDate: '2026-11-30',
        status: 'Active',
        agreementDocumentName: 'ABC_Manufacturing_MSA_Fleet_Agreement.pdf',
        agreementDocumentSize: '2.8 MB',
        agreementUploadDate: '2025-11-20'
      },
      {
        id: 'FLT-002',
        seaterCapacity: '32 Seater – Non AC',
        vehicleCount: 2,
        shiftFormat: 'Morning Shift (6:00 AM - 2:00 PM)',
        location: 'Talegaon Roster Hub',
        monthlyRatePerVehicleINR: 85000,
        totalMonthlyBillingINR: 170000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 22,
        extraHourRateINR: 150,
        tollParking: 'Inclusive',
        contractStartDate: '2025-12-01',
        contractEndDate: '2026-11-30',
        status: 'Active',
        agreementDocumentName: 'ABC_Manufacturing_MSA_Fleet_Agreement.pdf',
        agreementDocumentSize: '2.8 MB',
        agreementUploadDate: '2025-11-20'
      },
      {
        id: 'FLT-003',
        seaterCapacity: '06 Seater – Innova',
        vehicleCount: 2,
        shiftFormat: 'Executive On-Call / Ad-hoc Roster',
        location: 'Pune HQ Office',
        monthlyRatePerVehicleINR: 75000,
        totalMonthlyBillingINR: 150000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 16,
        extraHourRateINR: 100,
        tollParking: 'Exclusive / At Actuals',
        contractStartDate: '2025-12-01',
        contractEndDate: '2026-11-30',
        status: 'Active',
        agreementDocumentName: 'ABC_Manufacturing_MSA_Fleet_Agreement.pdf',
        agreementDocumentSize: '2.8 MB',
        agreementUploadDate: '2025-11-20'
      }
    ],
    agreementDocumentName: 'ABC_Manufacturing_MSA_Fleet_Agreement.pdf',
    agreementDocumentSize: '2.8 MB',
    agreementUploadDate: '2025-11-20',
    notes: 'Key client for annual staff transport renewal and EV bus expansion.'
  },
  {
    id: 'CLT-1002',
    code: 'CLT-1002',
    name: 'XYZ Automotive Components',
    clientType: 'New Client',
    industry: 'Automotive & Engineering',
    segment: 'Warehouse Logistics',
    city: 'Gurugram',
    state: 'Haryana',
    region: 'North',
    tier: 'Tier 1 (Enterprise)',
    turnoverCr: 800,
    employees: 4500,
    status: 'Active',
    accountOwner: 'Ananya Verma',
    website: 'www.xyzauto.demo',
    address: 'Sector 8, IMT Manesar, Gurugram',
    createdDate: '2026-07-20',
    contacts: [
      { id: 'CON-03', name: 'Harsh Vardhan', designation: 'Head of Supply Chain', email: 'h.vardhan@xyzauto.demo', phone: '+91 98110 77890', isPrimary: true },
      { id: 'CON-04', name: 'Anil Tyagi', designation: 'General Manager - Logistics', email: 'a.tyagi@xyzauto.demo', phone: '+91 98110 77892' }
    ],
    notes: 'Commercial proposal shared for 50,000 sq.ft warehouse management.'
  },
  {
    id: 'CLT-1003',
    code: 'CLT-1003',
    name: 'Global Foods & Beverages',
    clientType: 'New Client',
    industry: 'FMCG & Retail',
    segment: 'Cold Chain Logistics',
    city: 'Bengaluru',
    state: 'Karnataka',
    region: 'South',
    tier: 'Tier 1 (Enterprise)',
    turnoverCr: 1200,
    employees: 5800,
    status: 'Active',
    accountOwner: 'Vikram Malhotra',
    website: 'www.globalfoods.demo',
    address: 'Whitefield Tech Zone, Bengaluru',
    createdDate: '2026-08-05',
    contacts: [
      { id: 'CON-05', name: 'Meera Deshmukh', designation: 'Procurement Director', email: 'meera.d@globalfoods.demo', phone: '+91 97400 33211', isPrimary: true }
    ],
    notes: 'In final commercial negotiation for 18 temperature-controlled reefer trucks.'
  },
  {
    id: 'CLT-1004',
    code: 'CLT-1004',
    name: 'Prime Healthcare Solutions',
    clientType: 'Existing Client',
    industry: 'Healthcare & Pharma',
    segment: 'Last Mile Delivery',
    city: 'Hyderabad',
    state: 'Telangana',
    region: 'South',
    tier: 'Tier 2 (Mid-Market)',
    turnoverCr: 320,
    employees: 1800,
    status: 'Active',
    accountOwner: 'Pooja Nair',
    website: 'www.primehealth.demo',
    address: 'HITEC City, Hyderabad',
    createdDate: '2026-06-10',
    contacts: [
      { id: 'CON-06', name: 'Dr. Srinivas Rao', designation: 'Chief Logistics Officer', email: 'srao@primehealth.demo', phone: '+91 98480 12345', isPrimary: true }
    ],
    deployedFleets: [
      {
        id: 'FLT-004',
        seaterCapacity: '17 Seater Urbania',
        vehicleCount: 3,
        shiftFormat: '24/7 Rotational Roster (3 Shifts)',
        location: 'Hospital Campus & Diagnostics Roster',
        monthlyRatePerVehicleINR: 95000,
        totalMonthlyBillingINR: 285000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 20,
        extraHourRateINR: 140,
        tollParking: 'Inclusive',
        contractStartDate: '2026-06-15',
        contractEndDate: '2027-06-14',
        status: 'Active',
        agreementDocumentName: 'Prime_Healthcare_Transport_Agreement_Signed.pdf',
        agreementDocumentSize: '1.9 MB',
        agreementUploadDate: '2026-06-15'
      },
      {
        id: 'FLT-005',
        seaterCapacity: '06 Seater – Ertiga',
        vehicleCount: 5,
        shiftFormat: 'Split Shift (Morning 7-10 AM & Evening 5-8 PM)',
        location: 'Secunderabad Clinic Network',
        monthlyRatePerVehicleINR: 48000,
        totalMonthlyBillingINR: 240000,
        billingFrequency: 'Quarterly',
        extraKmRateINR: 14,
        extraHourRateINR: 90,
        tollParking: 'Exclusive / At Actuals',
        contractStartDate: '2026-06-15',
        contractEndDate: '2027-06-14',
        status: 'Active',
        agreementDocumentName: 'Prime_Healthcare_Transport_Agreement_Signed.pdf',
        agreementDocumentSize: '1.9 MB',
        agreementUploadDate: '2026-06-15'
      }
    ],
    agreementDocumentName: 'Prime_Healthcare_Transport_Agreement_Signed.pdf',
    agreementDocumentSize: '1.9 MB',
    agreementUploadDate: '2026-06-15',
    notes: 'Phase 1 active across 3 cities; Phase 2 proposal under evaluation.'
  },
  {
    id: 'CLT-1005',
    code: 'CLT-1005',
    name: 'Metro Logistics Hub',
    clientType: 'New Client',
    industry: 'E-commerce & Logistics',
    segment: 'Contract Logistics',
    city: 'Mumbai',
    state: 'Maharashtra',
    region: 'West',
    tier: 'Tier 2 (Mid-Market)',
    turnoverCr: 210,
    employees: 950,
    status: 'Active',
    accountOwner: 'Siddharth Roy',
    website: 'www.metrohub.demo',
    address: 'Bhiwandi Logistics Park, Mumbai',
    createdDate: '2026-08-18',
    contacts: [
      { id: 'CON-07', name: 'Amitabh Sen', designation: 'AVP - Business Operations', email: 'amitabh.s@metrohub.demo', phone: '+91 98200 99887', isPrimary: true }
    ],
    notes: 'Yard management and cross-docking RFP evaluation in progress.'
  },
  {
    id: 'CLT-1006',
    code: 'CLT-1006',
    name: 'Sunrise Industries',
    clientType: 'New Client',
    industry: 'Manufacturing & Heavy Industry',
    segment: 'Fleet Management',
    city: 'Ahmedabad',
    state: 'Gujarat',
    region: 'West',
    tier: 'Tier 2 (Mid-Market)',
    turnoverCr: 180,
    employees: 800,
    status: 'Active',
    accountOwner: 'Rahul Sharma',
    website: 'www.sunriseenergy.demo',
    address: 'Sanand Industrial Estate, Ahmedabad',
    createdDate: '2026-08-22',
    contacts: [
      { id: 'CON-08', name: 'Bhavin Patel', designation: 'General Manager - Admin', email: 'bhavin.p@sunriseenergy.demo', phone: '+91 98980 44321', isPrimary: true }
    ],
    notes: 'Solar park site staff transportation requirement for 20 vehicles.'
  },
  {
    id: 'CLT-1007',
    code: 'CLT-1007',
    name: 'Apex Tech Solutions',
    clientType: 'Existing Client',
    industry: 'Information Technology & ITES',
    segment: 'Corporate Travel',
    city: 'Bengaluru',
    state: 'Karnataka',
    region: 'South',
    tier: 'Tier 1 (Enterprise)',
    turnoverCr: 1500,
    employees: 7500,
    status: 'Active',
    accountOwner: 'Ananya Verma',
    website: 'www.apextech.demo',
    address: 'Electronic City Phase 1, Bengaluru',
    createdDate: '2025-09-12',
    contacts: [
      { id: 'CON-09', name: 'Deepa Narayan', designation: 'VP - Facilities & Real Estate', email: 'deepa.n@apextech.demo', phone: '+91 99000 77123', isPrimary: true }
    ],
    deployedFleets: [
      {
        id: 'FLT-006',
        seaterCapacity: '40 Seater – AC',
        vehicleCount: 6,
        shiftFormat: '24/7 Rotational Roster (3 Shifts)',
        location: 'Electronic City Campus Hub',
        monthlyRatePerVehicleINR: 120000,
        totalMonthlyBillingINR: 720000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 25,
        extraHourRateINR: 180,
        tollParking: 'Inclusive',
        contractStartDate: '2025-10-01',
        contractEndDate: '2026-09-30',
        status: 'Active',
        agreementDocumentName: 'Apex_Tech_Master_Service_Agreement_2026.pdf',
        agreementDocumentSize: '4.1 MB',
        agreementUploadDate: '2025-09-18'
      },
      {
        id: 'FLT-007',
        seaterCapacity: '50 Seater – AC',
        vehicleCount: 4,
        shiftFormat: 'General Shift (9:00 AM - 6:00 PM)',
        location: 'Whitefield - E-City Corridor',
        monthlyRatePerVehicleINR: 145000,
        totalMonthlyBillingINR: 580000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 28,
        extraHourRateINR: 200,
        tollParking: 'Inclusive',
        contractStartDate: '2025-10-01',
        contractEndDate: '2026-09-30',
        status: 'Active',
        agreementDocumentName: 'Apex_Tech_Master_Service_Agreement_2026.pdf',
        agreementDocumentSize: '4.1 MB',
        agreementUploadDate: '2025-09-18'
      },
      {
        id: 'FLT-008',
        seaterCapacity: '17 Seater – AC',
        vehicleCount: 6,
        shiftFormat: 'Night Shift (10:00 PM - 6:00 AM)',
        location: 'Safe Night Transport (Female Employee Routes)',
        monthlyRatePerVehicleINR: 70000,
        totalMonthlyBillingINR: 420000,
        billingFrequency: 'Monthly',
        extraKmRateINR: 18,
        extraHourRateINR: 120,
        tollParking: 'Exclusive / At Actuals',
        contractStartDate: '2025-10-01',
        contractEndDate: '2026-09-30',
        status: 'Active',
        agreementDocumentName: 'Apex_Tech_Master_Service_Agreement_2026.pdf',
        agreementDocumentSize: '4.1 MB',
        agreementUploadDate: '2025-09-18'
      },
      {
        id: 'FLT-009',
        seaterCapacity: '06 Seater – Innova',
        vehicleCount: 3,
        shiftFormat: 'Executive On-Call / Ad-hoc Roster',
        location: 'Leadership Travel & Airport Roster',
        monthlyRatePerVehicleINR: 80000,
        totalMonthlyBillingINR: 240000,
        billingFrequency: 'On call',
        extraKmRateINR: 17,
        extraHourRateINR: 110,
        tollParking: 'Exclusive / At Actuals',
        contractStartDate: '2025-10-01',
        contractEndDate: '2026-09-30',
        status: 'Active',
        agreementDocumentName: 'Apex_Tech_Master_Service_Agreement_2026.pdf',
        agreementDocumentSize: '4.1 MB',
        agreementUploadDate: '2025-09-18'
      }
    ],
    agreementDocumentName: 'Apex_Tech_Master_Service_Agreement_2026.pdf',
    agreementDocumentSize: '4.1 MB',
    agreementUploadDate: '2025-09-18',
    notes: 'Won 1.44 Cr annual shift transport agreement in Sep 2026.'
  },
  {
    id: 'CLT-1008',
    code: 'CLT-1008',
    name: 'Zenith Retail Warehousing',
    clientType: 'New Client',
    industry: 'FMCG & Retail',
    segment: 'Warehouse Logistics',
    city: 'Chennai',
    state: 'Tamil Nadu',
    region: 'South',
    tier: 'Tier 2 (Mid-Market)',
    turnoverCr: 290,
    employees: 1200,
    status: 'Active',
    accountOwner: 'Vikram Malhotra',
    website: 'www.zenithretail.demo',
    address: 'Sriperumbudur Industrial Corridor, Chennai',
    createdDate: '2026-07-10',
    contacts: [
      { id: 'CON-10', name: 'Karthik Subramanian', designation: 'Regional Supply Chain Head', email: 'karthik.s@zenithretail.demo', phone: '+91 98401 55667', isPrimary: true }
    ],
    notes: 'Lost on price margin to competitor in August. Follow-up planned for Q4.'
  }
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'OPP-2026-001',
    code: 'OPP-001',
    title: 'Chakan Plant EV Bus Employee Transport',
    clientId: 'CLT-1001',
    clientName: 'ABC Manufacturing Ltd',
    clientType: 'Existing Client',
    segment: 'Employee Transportation',
    serviceCategory: 'Staff Shuttle EV Commute',
    contractType: 'Annual Contract',
    dealValueINR: 18000000,
    monthlyValueINR: 1500000,
    stage: 'Commercial Negotiation',
    probability: 80,
    status: 'In Process',
    owner: 'Rahul Sharma',
    leadSource: 'Referral / Existing Client',
    expectedCloseDate: '2026-09-25',
    createdDate: '2026-08-01',
    lastActivityDate: '2026-09-04',
    nextFollowupDate: '2026-09-08',
    fleetSize: 12,
    vehicleType: '32-Seater Electric AC Bus',
    locations: 'Pune - Chakan Belt',
    competition: 'Starline Transporters',
    internalApprovalsRequired: true,
    delegatedDepartment: 'Legal & Compliance',
    delegatedOwner: 'Adv. Preeti Chawla (Legal)',
    delegationStatus: 'In Review',
    delegationMilestone: 'Power Escalation Tariff Clause Finalization',
    slaDaysRemaining: 2,
    notes: 'Management approved power escalation tariff model. Very high closure probability.'
  },
  {
    id: 'OPP-2026-002',
    code: 'OPP-002',
    title: 'Manesar Central Spares Hub 3PL Operations',
    clientId: 'CLT-1002',
    clientName: 'XYZ Automotive Components',
    clientType: 'New Client',
    segment: 'Warehouse Logistics',
    serviceCategory: '3PL Dedicated Warehousing',
    contractType: 'Annual Contract',
    dealValueINR: 24000000,
    monthlyValueINR: 2000000,
    stage: 'Client Review',
    probability: 70,
    status: 'In Process',
    owner: 'Ananya Verma',
    leadSource: 'Management Reference',
    expectedCloseDate: '2026-09-18',
    createdDate: '2026-07-22',
    lastActivityDate: '2026-09-05',
    nextFollowupDate: '2026-09-07',
    fleetSize: 5,
    vehicleType: 'Emergency Runner Vans',
    locations: 'Gurugram / Manesar',
    competition: 'Pinnacle Logistics',
    internalApprovalsRequired: true,
    delegatedDepartment: 'Operations',
    delegatedOwner: 'Manish Rawat (VP - Ops)',
    delegationStatus: 'Pending Action',
    delegationMilestone: 'Facility Inspection & Emergency Dispatch SOP Validation',
    slaDaysRemaining: 1,
    notes: 'Facility site inspection with client VP scheduled. Layout plan ready.'
  },
  {
    id: 'OPP-2026-003',
    code: 'OPP-003',
    title: 'Reefer Truck Secondary Distribution South',
    clientId: 'CLT-1003',
    clientName: 'Global Foods & Beverages',
    clientType: 'New Client',
    segment: 'Cold Chain Logistics',
    serviceCategory: 'Reefer Freight Distribution',
    contractType: 'Annual Contract',
    dealValueINR: 14400000,
    monthlyValueINR: 1200000,
    stage: 'Final Discussion',
    probability: 90,
    status: 'In Process',
    owner: 'Vikram Malhotra',
    leadSource: 'Direct Outreach / Cold BD',
    expectedCloseDate: '2026-09-20',
    createdDate: '2026-08-08',
    lastActivityDate: '2026-09-03',
    nextFollowupDate: '2026-09-06',
    fleetSize: 18,
    vehicleType: '20ft Temperature-Controlled Container Trucks',
    locations: 'Bengaluru, Chennai, Hyderabad',
    competition: 'Snowman Logistics',
    internalApprovalsRequired: true,
    delegatedDepartment: 'Fleet / Asset Management',
    delegatedOwner: 'Kishore Jha (Fleet Head)',
    delegationStatus: 'Approved & Handed Off',
    delegationMilestone: 'OEM Chassis Delivery Schedule Signed',
    slaDaysRemaining: 3,
    notes: 'Commercial terms agreed. Preparing final contract execution documents.'
  },
  {
    id: 'OPP-2026-004',
    code: 'OPP-004',
    title: 'Lab Sample Express Courier - Phase 2 Expansion',
    clientId: 'CLT-1004',
    clientName: 'Prime Healthcare Solutions',
    clientType: 'Existing Client',
    segment: 'Last Mile Delivery',
    serviceCategory: 'Express Diagnostic Logistics',
    contractType: 'Monthly Retainer',
    dealValueINR: 7200000,
    monthlyValueINR: 600000,
    stage: 'Proposal / Commercial Shared',
    probability: 65,
    status: 'In Process',
    owner: 'Pooja Nair',
    leadSource: 'Trade Show / Corporate Expo',
    expectedCloseDate: '2026-10-15',
    createdDate: '2026-08-12',
    lastActivityDate: '2026-08-28',
    nextFollowupDate: '2026-09-10',
    fleetSize: 25,
    vehicleType: 'Two-Wheelers & Small Vans',
    locations: 'Telangana & Andhra Pradesh',
    competition: 'MedExpress',
    internalApprovalsRequired: false,
    delegatedDepartment: 'BD',
    delegatedOwner: 'Pooja Nair',
    delegationStatus: 'Pending Action',
    delegationMilestone: 'Medical Director Proposal Presentation Scheduling',
    slaDaysRemaining: 4,
    notes: 'Scheduled multi-point temperature-controlled sample pickups across 80 clinics.'
  },
  {
    id: 'OPP-2026-005',
    code: 'OPP-005',
    title: 'Bhiwandi Hub Cross-Docking & Yard Operations',
    clientId: 'CLT-1005',
    clientName: 'Metro Logistics Hub',
    clientType: 'New Client',
    segment: 'Contract Logistics',
    serviceCategory: 'Hub & Yard Management',
    contractType: 'Annual Contract',
    dealValueINR: 12000000,
    monthlyValueINR: 1000000,
    stage: 'Internal Approval Pending',
    probability: 55,
    status: 'In Process',
    owner: 'Siddharth Roy',
    leadSource: 'Inbound Website Enquiry',
    expectedCloseDate: '2026-09-30',
    createdDate: '2026-08-20',
    lastActivityDate: '2026-09-01',
    nextFollowupDate: '2026-09-09',
    fleetSize: 8,
    vehicleType: 'Yard Prime Movers',
    locations: 'Bhiwandi, Mumbai',
    competition: 'Western Freight',
    internalApprovalsRequired: true,
    delegatedDepartment: 'Pricing & Commercials',
    delegatedOwner: 'Sunil Mehta (CFO)',
    delegationStatus: 'In Review',
    delegationMilestone: 'Weekend Shift Overtime Manpower Costing Sign-Off',
    slaDaysRemaining: 1,
    notes: 'Awaiting internal management sign-off on weekend shift manpower premiums.'
  },
  {
    id: 'OPP-2026-006',
    code: 'OPP-006',
    title: 'Sanand Solar Park Employee Commute (20 Tempo)',
    clientId: 'CLT-1006',
    clientName: 'Sunrise Industries',
    clientType: 'New Client',
    segment: 'Fleet Management',
    serviceCategory: 'Specialized Rural Commute Fleet',
    contractType: 'Annual Contract',
    dealValueINR: 9600000,
    monthlyValueINR: 800000,
    stage: 'Requirement Discussion',
    probability: 25,
    status: 'Open',
    owner: 'Rahul Sharma',
    leadSource: 'LinkedIn BD Campaign',
    expectedCloseDate: '2026-10-10',
    createdDate: '2026-08-24',
    lastActivityDate: '2026-08-30',
    nextFollowupDate: '2026-09-06',
    fleetSize: 20,
    vehicleType: '17-Seater Tempo Travellers',
    locations: 'Sanand & Viramgam, Gujarat',
    competition: 'Local Unorganized Fleet Owners',
    internalApprovalsRequired: false,
    delegatedDepartment: 'Operations',
    delegatedOwner: 'Rahul Sharma',
    delegationStatus: 'Pending Action',
    delegationMilestone: 'Route & Toll Feasibility Survey Report Creation',
    slaDaysRemaining: 2,
    notes: 'Route survey completed. Calculating detailed power and toll structure.'
  },
  {
    id: 'OPP-2026-007',
    code: 'OPP-007',
    title: 'Electronic City Tech Campus Shift Fleet',
    clientId: 'CLT-1007',
    clientName: 'Apex Tech Solutions',
    clientType: 'Existing Client',
    segment: 'Corporate Travel',
    serviceCategory: 'Corporate Shift Transportation',
    contractType: 'Annual Contract',
    dealValueINR: 14400000,
    monthlyValueINR: 1200000,
    stage: 'Won',
    probability: 100,
    status: 'Won',
    owner: 'Ananya Verma',
    leadSource: 'Referral / Existing Client',
    expectedCloseDate: '2026-09-01',
    createdDate: '2026-07-05',
    lastActivityDate: '2026-09-02',
    nextFollowupDate: '2026-09-15',
    fleetSize: 40,
    vehicleType: '25 Tempo Travellers + 15 Sedans',
    locations: 'Bengaluru IT Belt',
    competition: 'Ola Corporate',
    internalApprovalsRequired: true,
    delegatedDepartment: 'Operations',
    delegatedOwner: 'Operations Team Bangalore',
    delegationStatus: 'Action Completed',
    delegationMilestone: 'GPS Telematics & Driver Security Verification Complete',
    slaDaysRemaining: 0,
    notes: 'Won Deal! Contract executed for 24 months. Fleet onboarding in progress.'
  },
  {
    id: 'OPP-2026-008',
    code: 'OPP-008',
    title: 'Sriperumbudur FMCG Fulfillment Hub 80K Sqft',
    clientId: 'CLT-1008',
    clientName: 'Zenith Retail Warehousing',
    clientType: 'New Client',
    segment: 'Warehouse Logistics',
    serviceCategory: '3PL Fulfillment Hub',
    contractType: 'Annual Contract',
    dealValueINR: 19200000,
    monthlyValueINR: 1600000,
    stage: 'Lost',
    probability: 0,
    status: 'Lost',
    owner: 'Vikram Malhotra',
    leadSource: 'Tender / RFP Portal',
    expectedCloseDate: '2026-08-25',
    createdDate: '2026-07-12',
    lastActivityDate: '2026-08-25',
    nextFollowupDate: '2026-11-01',
    fleetSize: 0,
    vehicleType: 'N/A',
    locations: 'Chennai',
    competition: 'TVS Supply Chain',
    lostReason: 'Price Issue',
    lostRemarks: 'Competitor undercut by 11% using un-racked storage configuration.',
    internalApprovalsRequired: true,
    delegatedDepartment: 'BD',
    delegatedOwner: 'Vikram Malhotra',
    delegationStatus: 'Action Completed',
    delegationMilestone: 'Loss Analysis Recorded for Q4 Secondary Re-engagement',
    slaDaysRemaining: 0,
    notes: 'Lost to TVS Supply Chain on price. Will re-engage in Q4 for secondary hub.'
  }
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'ACT-5001',
    type: 'Physical Meeting',
    clientId: 'CLT-1002',
    clientName: 'XYZ Automotive Components',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-002',
    opportunityTitle: 'Manesar Central Spares Hub 3PL Operations',
    date: '2026-09-05',
    time: '14:30',
    conductedBy: 'Ananya Verma',
    contactPerson: 'Harsh Vardhan',
    location: 'Client HQ - Gurugram',
    keyDiscussion: 'Presented 3D warehouse layout, racking capacity calculations, and WMS software integration capabilities.',
    outcome: 'Technical team thoroughly convinced. Scheduled facility site visit on 7th Sept.',
    actionItems: 'Provide emergency turnaround SOP by 6th Sept evening.',
    nextFollowupDate: '2026-09-07',
    status: 'Completed'
  },
  {
    id: 'ACT-5002',
    type: 'Commercial Negotiation',
    clientId: 'CLT-1001',
    clientName: 'ABC Manufacturing Ltd',
    clientType: 'Existing Client',
    opportunityId: 'OPP-2026-001',
    opportunityTitle: 'Chakan Plant EV Bus Employee Transport',
    date: '2026-09-04',
    time: '11:00',
    conductedBy: 'Rahul Sharma',
    contactPerson: 'Rajesh Kulkarni',
    location: 'ABC Chakan Plant, Pune',
    keyDiscussion: 'Discussed capital expense amortization of fast charging stations vs per-km tariff models.',
    outcome: 'Agreed on ₹78/km base rate with quarterly power cost true-up clause.',
    actionItems: 'Submit revised per-km power escalation model to Rajesh by Monday morning.',
    nextFollowupDate: '2026-09-08',
    status: 'Completed'
  },
  {
    id: 'ACT-5003',
    type: 'Commercial Negotiation',
    clientId: 'CLT-1003',
    clientName: 'Global Foods & Beverages',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-003',
    opportunityTitle: 'Reefer Truck Secondary Distribution South',
    date: '2026-09-03',
    time: '15:00',
    conductedBy: 'Vikram Malhotra',
    contactPerson: 'Meera Deshmukh',
    location: 'Virtual Conference',
    keyDiscussion: 'Negotiated temp variation penalty clauses and insurance liability limits for cold chain transit.',
    outcome: 'Agreed to waive software API integration fee in exchange for a 2-year firm contract.',
    actionItems: 'Final commercial sign-off meeting with MD & Procurement.',
    nextFollowupDate: '2026-09-06',
    status: 'Completed'
  },
  {
    id: 'ACT-5004',
    type: 'Physical Meeting',
    clientId: 'CLT-1007',
    clientName: 'Apex Tech Solutions',
    clientType: 'Existing Client',
    opportunityId: 'OPP-2026-007',
    opportunityTitle: 'Electronic City Tech Campus Shift Fleet',
    date: '2026-09-02',
    time: '10:30',
    conductedBy: 'Ananya Verma',
    contactPerson: 'Deepa Narayan',
    location: 'Apex Tech Electronic City Campus',
    keyDiscussion: 'Contract handover and driver background verification camp scheduling.',
    outcome: 'Master service agreement signed for 24 months. Handover done to Operations Team.',
    actionItems: 'Deploy 40 vehicles with GPS tracking by Sept 15.',
    nextFollowupDate: '2026-09-15',
    status: 'Completed'
  },
  {
    id: 'ACT-5005',
    type: 'Phone Call',
    clientId: 'CLT-1005',
    clientName: 'Metro Logistics Hub',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-005',
    opportunityTitle: 'Bhiwandi Hub Cross-Docking & Yard Operations',
    date: '2026-09-01',
    time: '16:00',
    conductedBy: 'Siddharth Roy',
    contactPerson: 'Amitabh Sen',
    location: 'Phone Call',
    keyDiscussion: 'Clarified container turnaround time definitions and dock crane operator shifts.',
    outcome: 'Client will keep proposal window open until 10th Sept for revised manpower quotation.',
    actionItems: 'Obtain COO & Finance sign-off on weekend shift labor rates.',
    nextFollowupDate: '2026-09-09',
    status: 'Completed'
  },
  {
    id: 'ACT-5006',
    type: 'Site Visit',
    clientId: 'CLT-1006',
    clientName: 'Sunrise Industries',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-006',
    opportunityTitle: 'Sanand Solar Park Employee Commute (20 Tempo)',
    date: '2026-08-30',
    time: '09:00',
    conductedBy: 'Rahul Sharma',
    contactPerson: 'Bhavin Patel',
    location: 'Sanand Site, Gujarat',
    keyDiscussion: 'Inspected pickup points and road terrain for technician commute.',
    outcome: 'Route mapped. Route survey feasibility report prepared.',
    actionItems: 'Conduct detailed route survey and toll analysis with operations.',
    nextFollowupDate: '2026-09-06',
    status: 'Completed'
  }
];

export const INITIAL_FOLLOWUPS: Followup[] = [
  {
    id: 'FOL-001',
    clientId: 'CLT-1003',
    clientName: 'Global Foods & Beverages',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-003',
    opportunityTitle: 'Reefer Truck Secondary Distribution South',
    dueDate: '2026-09-06',
    assignedTo: 'Vikram Malhotra',
    type: 'Commercial Sign-off Meeting',
    priority: 'High',
    description: 'Final commercial sign-off meeting with MD & Procurement for 18 reefer trucks.',
    status: 'Pending'
  },
  {
    id: 'FOL-002',
    clientId: 'CLT-1006',
    clientName: 'Sunrise Industries',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-006',
    opportunityTitle: 'Sanand Solar Park Employee Commute (20 Tempo)',
    dueDate: '2026-09-06',
    assignedTo: 'Rahul Sharma',
    type: 'Route Survey Report & Quote',
    priority: 'Medium',
    description: 'Share route survey findings and revised commercial quote.',
    status: 'Pending'
  },
  {
    id: 'FOL-003',
    clientId: 'CLT-1002',
    clientName: 'XYZ Automotive Components',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-002',
    opportunityTitle: 'Manesar Central Spares Hub 3PL Operations',
    dueDate: '2026-09-07',
    assignedTo: 'Ananya Verma',
    type: 'Warehouse Site Inspection',
    priority: 'High',
    description: 'Facility site inspection with client VP Supply Chain at Manesar hub.',
    status: 'Pending'
  },
  {
    id: 'FOL-004',
    clientId: 'CLT-1001',
    clientName: 'ABC Manufacturing Ltd',
    clientType: 'Existing Client',
    opportunityId: 'OPP-2026-001',
    opportunityTitle: 'Chakan Plant EV Bus Employee Transport',
    dueDate: '2026-09-08',
    assignedTo: 'Rahul Sharma',
    type: 'Legal Revision Submission',
    priority: 'High',
    description: 'Submit revised per-km power escalation model to Rajesh Kulkarni.',
    status: 'Pending'
  },
  {
    id: 'FOL-005',
    clientId: 'CLT-1005',
    clientName: 'Metro Logistics Hub',
    clientType: 'New Client',
    opportunityId: 'OPP-2026-005',
    opportunityTitle: 'Bhiwandi Hub Cross-Docking & Yard Operations',
    dueDate: '2026-09-09',
    assignedTo: 'Siddharth Roy',
    type: 'Commercial RFP Bid Submission',
    priority: 'Medium',
    description: 'Submit revised commercial bid after management sign-off on weekend shifts.',
    status: 'Pending'
  },
  {
    id: 'FOL-006',
    clientId: 'CLT-1004',
    clientName: 'Prime Healthcare Solutions',
    clientType: 'Existing Client',
    opportunityId: 'OPP-2026-004',
    opportunityTitle: 'Lab Sample Express Courier - Phase 2 Expansion',
    dueDate: '2026-09-10',
    assignedTo: 'Pooja Nair',
    type: 'Proposal Presentation',
    priority: 'Medium',
    description: 'Schedule proposal presentation with Medical Director for Phase 2 expansion.',
    status: 'Pending'
  }
];

export const INITIAL_INTERNAL_TASKS: InternalTask[] = [
  {
    id: 'INT-3001',
    department: 'Operations',
    title: 'Emergency 4-hr dispatch turnaround cost modeling for XYZ Auto',
    clientId: 'CLT-1002',
    clientName: 'XYZ Automotive Components',
    opportunityId: 'OPP-2026-002',
    opportunityTitle: 'Manesar Central Spares Hub 3PL Operations',
    assignedTo: 'Ananya Verma',
    assignedBy: 'Manish Rawat (VP - Ops)',
    dueDate: '2026-09-06',
    priority: 'High',
    status: 'Completed',
    requestDetails: 'Determine manpower and runner vehicle cost for 4-hr emergency dispatch SLA.',
    responseNotes: 'Simulated 3 dedicated dispatch runners with 2 shifts. Approved ₹1,10,000/mo rider with 25% gross margin.',
    actionDate: '2026-09-05'
  },
  {
    id: 'INT-3002',
    department: 'Finance & Accounts',
    title: 'Electricity escalation capping sign-off for ABC EV Bus contract',
    clientId: 'CLT-1001',
    clientName: 'ABC Manufacturing Ltd',
    opportunityId: 'OPP-2026-001',
    opportunityTitle: 'Chakan Plant EV Bus Employee Transport',
    assignedTo: 'Rahul Sharma',
    assignedBy: 'Sunil Mehta (CFO)',
    dueDate: '2026-09-05',
    priority: 'High',
    status: 'Approved',
    requestDetails: 'Approval to link energy surcharge directly to State DISCOM industrial power tariff.',
    responseNotes: 'CFO signed off email approval. Risk capped to max 5% operational variance.',
    actionDate: '2026-09-04'
  },
  {
    id: 'INT-3003',
    department: 'Fleet / Asset Management',
    title: 'Fleet availability verification for 18 Reefer Trucks (Global Foods)',
    clientId: 'CLT-1003',
    clientName: 'Global Foods & Beverages',
    opportunityId: 'OPP-2026-003',
    opportunityTitle: 'Reefer Truck Secondary Distribution South',
    assignedTo: 'Vikram Malhotra',
    assignedBy: 'Kishore Jha (Fleet Head)',
    dueDate: '2026-09-06',
    priority: 'Urgent',
    status: 'Completed',
    requestDetails: 'Verify vehicle delivery timelines from OEM for 18 refrigerated chassis.',
    responseNotes: '10 vehicles ready in Bangalore depot, 8 to be delivered by Oct 5th. Phased rollout agreed.',
    actionDate: '2026-09-03'
  },
  {
    id: 'INT-3004',
    department: 'Pricing & Commercials',
    title: 'Weekend overtime & 24x7 shift cost evaluation for Metro Logistics Hub',
    clientId: 'CLT-1005',
    clientName: 'Metro Logistics Hub',
    opportunityId: 'OPP-2026-005',
    opportunityTitle: 'Bhiwandi Hub Cross-Docking & Yard Operations',
    assignedTo: 'Siddharth Roy',
    assignedBy: 'Manish Rawat & Finance Team',
    dueDate: '2026-09-08',
    priority: 'Urgent',
    status: 'Pending',
    requestDetails: 'Finalize minimum billing rate per container move with 24x7 dock labor and overtime.',
    responseNotes: 'Cost sheet submitted to Managing Director for review in Monday operational review.',
    actionDate: '2026-09-02'
  },
  {
    id: 'INT-3005',
    department: 'Legal & Compliance',
    title: 'Contract terms and indemnification clause review for Apex Tech Solutions MSA',
    clientId: 'CLT-1007',
    clientName: 'Apex Tech Solutions',
    opportunityId: 'OPP-2026-007',
    opportunityTitle: 'Electronic City Tech Campus Shift Fleet',
    assignedTo: 'Ananya Verma',
    assignedBy: 'Adv. Preeti Chawla (Legal Head)',
    dueDate: '2026-09-01',
    priority: 'High',
    status: 'Approved',
    requestDetails: 'Review data privacy, employee safety liability & 30-day payment terms.',
    responseNotes: 'Approved Master Agreement document returned and executed with client.',
    actionDate: '2026-08-31'
  },
  {
    id: 'INT-3006',
    department: 'Pricing & Commercials',
    title: 'Tariff discount approval request for Sunrise Industries Solar Fleet',
    clientId: 'CLT-1006',
    clientName: 'Sunrise Industries',
    opportunityId: 'OPP-2026-006',
    opportunityTitle: 'Sanand Solar Park Employee Commute (20 Tempo)',
    assignedTo: 'Rahul Sharma',
    assignedBy: 'Sunil Mehta (CFO)',
    dueDate: '2026-09-06',
    priority: 'Medium',
    status: 'Rejected',
    requestDetails: 'Request 14% tariff discount to beat local Gujarat unorganized fleet competitors.',
    responseNotes: 'Rejected: Unapproved margin erosion below 18%. Require revised fuel escalation clause instead.',
    actionDate: '2026-09-02'
  }
];

export const INITIAL_DOCUMENTS: CRMDocument[] = [
  {
    id: 'DOC-101',
    name: 'ABC_EV_Commercial_Proposal_v2.pdf',
    originalFilename: 'ABC_EV_Commercial_Proposal_v2.pdf',
    opportunityId: 'OPP-2026-001',
    opportunityTitle: 'Chakan Plant EV Bus Employee Transport',
    clientId: 'CLT-1001',
    clientName: 'ABC Manufacturing Ltd',
    stage: 'Commercial Negotiation',
    documentType: 'Commercial Proposal PDF',
    fileSize: '2.4 MB',
    fileExtension: 'pdf',
    uploadedBy: 'Rahul Sharma',
    uploadedDate: '2026-09-04',
    notes: 'Approved per-km power escalation tariff model annexure included.'
  },
  {
    id: 'DOC-102',
    name: 'XYZ_Manesar_Racking_Layout_3D.dwg',
    originalFilename: 'XYZ_Manesar_Racking_Layout_3D.dwg',
    opportunityId: 'OPP-2026-002',
    opportunityTitle: 'Manesar Central Spares Hub 3PL Operations',
    clientId: 'CLT-1002',
    clientName: 'XYZ Automotive Components',
    stage: 'Client Review',
    documentType: 'Technical Scope / Layout PDF',
    fileSize: '4.8 MB',
    fileExtension: 'dwg',
    uploadedBy: 'Ananya Verma',
    uploadedDate: '2026-09-05',
    notes: '3D warehouse simulation and pallet slotting diagram.'
  },
  {
    id: 'DOC-103',
    name: 'GlobalFoods_Reefer_ColdChain_SLA.docx',
    originalFilename: 'GlobalFoods_Reefer_ColdChain_SLA.docx',
    opportunityId: 'OPP-2026-003',
    opportunityTitle: 'Reefer Truck Secondary Distribution South',
    clientId: 'CLT-1003',
    clientName: 'Global Foods & Beverages',
    stage: 'Final Discussion',
    documentType: 'Signed SLA / Master Contract',
    fileSize: '1.1 MB',
    fileExtension: 'docx',
    uploadedBy: 'Vikram Malhotra',
    uploadedDate: '2026-09-03',
    notes: 'SLA penalty clauses and temp monitoring API waiver terms.'
  },
  {
    id: 'DOC-104',
    name: 'ApexTech_Signed_MSA_MasterContract.pdf',
    originalFilename: 'ApexTech_Signed_MSA_MasterContract.pdf',
    opportunityId: 'OPP-2026-007',
    opportunityTitle: 'Electronic City Tech Campus Shift Fleet',
    clientId: 'CLT-1007',
    clientName: 'Apex Tech Solutions',
    stage: 'Won',
    documentType: 'Signed SLA / Master Contract',
    fileSize: '3.6 MB',
    fileExtension: 'pdf',
    uploadedBy: 'Ananya Verma',
    uploadedDate: '2026-09-02',
    notes: 'Signed 24-month contract for 40 fleet units.'
  },
  {
    id: 'DOC-105',
    name: 'Metro_Bhiwandi_Yard_Costing_Matrix.xlsx',
    originalFilename: 'Metro_Bhiwandi_Yard_Costing_Matrix.xlsx',
    opportunityId: 'OPP-2026-005',
    opportunityTitle: 'Bhiwandi Hub Cross-Docking & Yard Operations',
    clientId: 'CLT-1005',
    clientName: 'Metro Logistics Hub',
    stage: 'Internal Approval Pending',
    documentType: 'Commercial Rate Card / Quotation',
    fileSize: '820 KB',
    fileExtension: 'xlsx',
    uploadedBy: 'Siddharth Roy',
    uploadedDate: '2026-09-01',
    notes: 'Weekend shift labor rates and dock equipment throughput simulation.'
  },
  {
    id: 'DOC-106',
    name: 'Sunrise_Sanand_Route_Survey_Map.pdf',
    originalFilename: 'Sunrise_Sanand_Route_Survey_Map.pdf',
    opportunityId: 'OPP-2026-006',
    opportunityTitle: 'Sanand Solar Park Employee Commute (20 Tempo)',
    clientId: 'CLT-1006',
    clientName: 'Sunrise Industries',
    stage: 'Requirement Discussion',
    documentType: 'Client Requirement / RFP Scope',
    fileSize: '5.2 MB',
    fileExtension: 'pdf',
    uploadedBy: 'Rahul Sharma',
    uploadedDate: '2026-08-30',
    notes: 'GPS route mapping and toll booth turnaround timings.'
  }
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'BD-01',
    name: 'Rahul Sharma',
    title: 'Senior BD Manager',
    email: 'rahul.s@corpbd.com',
    phone: '+91 98201 22334',
    region: 'North & West',
    annualTargetINR: 50000000,
    achievedINR: 36800000,
    activeOppsCount: 4,
    avatarBg: '#3b82f6',
    status: 'Active'
  },
  {
    id: 'BD-02',
    name: 'Ananya Verma',
    title: 'BD Lead - Enterprise',
    email: 'ananya.v@corpbd.com',
    phone: '+91 98110 44556',
    region: 'West & South',
    annualTargetINR: 60000000,
    achievedINR: 48400000,
    activeOppsCount: 5,
    avatarBg: '#8b5cf6',
    status: 'Active'
  },
  {
    id: 'BD-03',
    name: 'Vikram Malhotra',
    title: 'Key Accounts Director',
    email: 'vikram.m@corpbd.com',
    phone: '+91 99300 77889',
    region: 'South Region',
    annualTargetINR: 80000000,
    achievedINR: 62000000,
    activeOppsCount: 6,
    avatarBg: '#10b981',
    status: 'Active'
  },
  {
    id: 'BD-04',
    name: 'Pooja Nair',
    title: 'BD Executive - North',
    email: 'pooja.n@corpbd.com',
    phone: '+91 98450 11223',
    region: 'North & Central',
    annualTargetINR: 35000000,
    achievedINR: 24500000,
    activeOppsCount: 3,
    avatarBg: '#f59e0b',
    status: 'Active'
  },
  {
    id: 'BD-05',
    name: 'Siddharth Roy',
    title: 'BD Executive - West',
    email: 'siddharth.r@corpbd.com',
    phone: '+91 98230 99001',
    region: 'West Region',
    annualTargetINR: 40000000,
    achievedINR: 28000000,
    activeOppsCount: 4,
    avatarBg: '#06b6d4',
    status: 'Active'
  }
];

export const INITIAL_SEGMENTS: BusinessSegment[] = [
  {
    id: 'SEG-01',
    name: 'Employee Transportation',
    category: 'Corporate Mobility',
    targetMarginPct: 22,
    leadOwner: 'Rahul Sharma',
    description: 'Corporate employee commute, cab fleet operations, shuttle buses and green EV transport.',
    activeClientsCount: 8,
    pipelineValueINR: 42000000
  },
  {
    id: 'SEG-02',
    name: 'Warehouse Logistics',
    category: 'Supply Chain & 3PL',
    targetMarginPct: 25,
    leadOwner: 'Ananya Verma',
    description: 'Grade-A dedicated warehousing, multi-client distribution centers, WMS software and inventory management.',
    activeClientsCount: 6,
    pipelineValueINR: 58000000
  },
  {
    id: 'SEG-03',
    name: 'Fleet Management',
    category: 'Enterprise Fleet',
    targetMarginPct: 18,
    leadOwner: 'Pooja Nair',
    description: 'Enterprise fleet leasing, telematics, maintenance, fuel management and dedicated corporate drivers.',
    activeClientsCount: 5,
    pipelineValueINR: 28000000
  },
  {
    id: 'SEG-04',
    name: 'Contract Logistics',
    category: 'End-to-End 3PL',
    targetMarginPct: 20,
    leadOwner: 'Siddharth Roy',
    description: 'End-to-end 3PL / 4PL long-term contracts, supply chain planning, multimodal transport and packaging.',
    activeClientsCount: 4,
    pipelineValueINR: 34000000
  },
  {
    id: 'SEG-05',
    name: 'Corporate Travel',
    category: 'Executive Mobility',
    targetMarginPct: 28,
    leadOwner: 'Rahul Sharma',
    description: 'Executive VIP travel, airport transfers, corporate event logistics and luxury car rentals.',
    activeClientsCount: 7,
    pipelineValueINR: 22000000
  },
  {
    id: 'SEG-06',
    name: 'Supply Chain Solutions',
    category: 'Consulting & Multimodal',
    targetMarginPct: 24,
    leadOwner: 'Vikram Malhotra',
    description: 'Consulting, network optimization, freight forwarding, customs clearance and port handling.',
    activeClientsCount: 5,
    pipelineValueINR: 48000000
  },
  {
    id: 'SEG-07',
    name: 'Last Mile Delivery',
    category: 'Urban E-commerce',
    targetMarginPct: 16,
    leadOwner: 'Pooja Nair',
    description: 'E-commerce intracity delivery, hyper-local courier, dark store dispatches and return logistics.',
    activeClientsCount: 3,
    pipelineValueINR: 19000000
  },
  {
    id: 'SEG-08',
    name: 'Cold Chain Logistics',
    category: 'Temperature-Controlled',
    targetMarginPct: 26,
    leadOwner: 'Vikram Malhotra',
    description: 'Temperature-controlled reefer trucks, cold storage, perishable pharma & food distribution.',
    activeClientsCount: 4,
    pipelineValueINR: 36000000
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Devika Pangam',
    email: 'devika.p@rajmudragroup.com',
    role: 'System Administrator',
    role_name: 'System Administrator',
    status: 'Active',
    allowed_tabs: [
      'tab-dashboard', 'tab-clients', 'tab-team', 'tab-segments',
      'tab-opportunities', 'tab-calculator', 'tab-activities', 'tab-followups',
      'tab-internal', 'tab-documents', 'tab-review', 'tab-users'
    ]
  },
  {
    id: 'USR-002',
    name: 'Rahul Sharma',
    email: 'rahul.s@corpbd.com',
    role: 'BD Manager',
    role_name: 'Senior BD Manager',
    status: 'Active',
    allowed_tabs: [
      'tab-dashboard', 'tab-clients', 'tab-team', 'tab-opportunities',
      'tab-calculator', 'tab-activities', 'tab-followups', 'tab-internal', 'tab-documents', 'tab-review'
    ]
  },
  {
    id: 'USR-003',
    name: 'Ananya Verma',
    email: 'ananya.v@corpbd.com',
    role: 'BD Executive',
    role_name: 'BD Lead - Enterprise',
    status: 'Active',
    allowed_tabs: [
      'tab-dashboard', 'tab-clients', 'tab-opportunities', 'tab-calculator',
      'tab-activities', 'tab-followups', 'tab-documents'
    ]
  },
  {
    id: 'USR-004',
    name: 'Vikram Malhotra',
    email: 'vikram.m@corpbd.com',
    role: 'BD Manager',
    role_name: 'Key Accounts Director',
    status: 'Active',
    allowed_tabs: [
      'tab-dashboard', 'tab-clients', 'tab-team', 'tab-opportunities',
      'tab-calculator', 'tab-activities', 'tab-followups', 'tab-internal', 'tab-documents', 'tab-review'
    ]
  },
  {
    id: 'USR-005',
    name: 'Executive Reviewer',
    email: 'management@corpbd.com',
    role: 'Management Reviewer',
    role_name: 'Executive Leadership',
    status: 'Active',
    allowed_tabs: [
      'tab-dashboard', 'tab-review', 'tab-opportunities', 'tab-calculator', 'tab-team', 'tab-segments', 'tab-documents'
    ]
  }
];

export const PIPELINE_STAGES = [
  'New Enquiry',
  'Initial Contact',
  'Requirement Discussion',
  'Meeting Scheduled',
  'Meeting Completed',
  'Requirement Received',
  'Proposal Under Preparation',
  'Internal Approval Pending',
  'Proposal / Commercial Shared',
  'Client Review',
  'Follow-up',
  'Commercial Negotiation',
  'Final Discussion',
  'Won',
  'Lost',
  'On Hold'
];

export const DOCUMENT_TYPES = [
  'Commercial Proposal PDF',
  'Email Approval PDF',
  'Commercial Rate Card / Quotation',
  'Signed SLA / Master Contract',
  'Technical Scope / Layout PDF',
  'Presentation Pitch Deck',
  'Minutes of Meeting (MOM)',
  'Client Requirement / RFP Scope',
  'Other Document'
];

export const FLEET_SEATER_CAPACITIES: FleetSeaterCapacity[] = [
  '17 Seater – Non AC',
  '17 Seater – AC',
  '32 Seater – Non AC',
  '32 Seater – AC',
  '40 Seater – Non AC',
  '40 Seater – AC',
  '50 Seater – Non AC',
  '50 Seater – AC',
  '17 Seater Urbania',
  '06 Seater – Ertiga',
  '06 Seater – Innova'
];

export const SHIFT_FORMAT_PRESETS = [
  'General Shift (9:00 AM - 6:00 PM)',
  'Morning Shift (6:00 AM - 2:00 PM)',
  'Afternoon Shift (2:00 PM - 10:00 PM)',
  'Night Shift (10:00 PM - 6:00 AM)',
  '24/7 Rotational Roster (3 Shifts)',
  'Split Shift (Morning 7-10 AM & Evening 5-8 PM)',
  'Dedicated Plant Shift (8:00 AM - 4:30 PM)',
  'Executive On-Call / Ad-hoc Roster'
];

export const BILLING_FREQUENCIES: BillingFrequency[] = [
  'Monthly',
  'Quarterly',
  'On call'
];

export const LEAD_SOURCES = [
  'Direct Outreach / Cold BD',
  'Referral / Existing Client',
  'Inbound Website Enquiry',
  'Trade Show / Corporate Expo',
  'Management Reference',
  'LinkedIn BD Campaign',
  'Tender / RFP Portal',
  'Partner Channel'
];

export const INDUSTRIES = [
  'Automotive & Engineering',
  'Information Technology & ITES',
  'Healthcare & Pharma',
  'FMCG & Retail',
  'Manufacturing & Heavy Industry',
  'E-commerce & Logistics',
  'Banking & Financial Services',
  'Consulting & Professional'
];

export const DEPARTMENTS = [
  'Operations',
  'Pricing & Commercials',
  'Management',
  'Finance & Accounts',
  'Legal & Compliance',
  'Fleet / Asset Management',
  'Human Resources',
  'IT & Systems',
  'BD'
];
